#!/bin/bash

echo -n "Enter some number > "
read number 
echo "You entered: $number"

n=$number
sd=0
rev=0

while [ $n -gt 0 ]
do
    sd=$(( $n % 10 ))
    rev=$(( $rev * 10 + $sd ))
    n=$(( $n / 10 ))
done
echo "Reverse number of entered digit is $rev"
